spec:
  structures:
    - formBlocks
  label: Segments
  description: "A segmented control component using radio buttons or checkboxes with optional icons."
  icon: rectangle
  tags: []

blueprint:
  name:
  options: []
  title:
  required: false
  iconOnly: false
  multiple: false
  keepStateOnRefresh: false

preview:

_inputs:
  name:
    type: text
    comment: The name attribute for the radio button group.
  options:
    type: array
    comment: Array of segment options with value, label, icon, and checked state.
    options:
      structures: _structures.option
  title:
    type: text
    comment: Optional title text for the fieldset.
  required:
    type: switch
    comment: Whether the field is required.
  iconOnly:
    type: switch
    comment: When true, labels are used as tooltips instead of being displayed as text.
  multiple:
    type: switch
    comment: When true, uses checkboxes for multiple selection instead of radio buttons for single selection.
  keepStateOnRefresh:
    type: switch
    comment: When true, allows the browser to remember state on page refresh.

_structures:
  option:
    values:
      - label: Segment Option
        icon: list
        value:
          value:
          label:
          icon:
          checked: false
        _inputs:
          value:
            type: text
            comment: The value attribute for this segment option (submitted with the form).
          label:
            type: text
            comment: The display text for this segment option.
          icon:
            type: select
            comment: Optional icon to display in the segment.
            options:
              values: _select_data.icons
          checked:
            type: switch
            comment: Whether this option is checked by default.
