/**
 * Generates `.cloudcannon/data/icons.yml` (the `data.icons` dataset) from `src/icons/`.
 * An id with no SVG is a broken thumbnail and an SVG with no id is unselectable; neither errors.
 *
 *   node scripts/icons/sync.mjs           regenerate the data file from src/icons/
 *   node scripts/icons/sync.mjs --check   verify the data file matches disk (CI)
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative, sep } from "node:path";
import { iconKeyFromPath } from "../../src/components/utils/iconKey.mjs";

const mode = process.argv.includes("--check") ? "check" : "write";
const root = join(dirname(new URL(import.meta.url).pathname), "..", "..");

const iconsDir = join(root, "src", "icons");
const dataPath = join(root, ".cloudcannon", "data", "icons.yml");
const dataLabel = relative(root, dataPath);

/** Ids are emitted unquoted, so keep them to characters YAML never reinterprets. */
const SAFE_ID = /^[a-z0-9]+(?:[-/][a-z0-9]+)*$/;

function listIcons(dir, base = dir, out = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const absolute = join(dir, entry.name);

    if (entry.isDirectory()) {
      listIcons(absolute, base, out);
    } else if (entry.isFile() && entry.name.endsWith(".svg")) {
      out.push(iconKeyFromPath(relative(base, absolute).split(sep).join("/")));
    }
  }
  return out;
}

/** Applied only to the leaf of an id with a directory prefix, never to a top-level icon. */
const LEAF_LABELS = {
  github: "GitHub",
  gitlab: "GitLab",
  linkedin: "LinkedIn",
  tiktok: "TikTok",
  youtube: "YouTube",
};

function titleizeSegment(segment) {
  return segment
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

/** `social/github` -> `Social/GitHub`. Keep the prefix: editors filter the picker by "social". */
function titleize(id) {
  const segments = id.split("/");

  return segments
    .map((segment, index) => {
      const isLeaf = index === segments.length - 1;
      const hasPrefix = segments.length > 1;

      return isLeaf && hasPrefix && LEAF_LABELS[segment]
        ? LEAF_LABELS[segment]
        : titleizeSegment(segment);
    })
    .join("/");
}

const ids = listIcons(iconsDir).sort();

const invalid = ids.filter((id) => !SAFE_ID.test(id));

if (invalid.length) {
  console.error(`Unsupported icon filename(s) under ${relative(root, iconsDir)}:`);
  for (const id of invalid) console.error(`   ${id}.svg`);
  console.error("\nUse lowercase kebab-case names so the generated ids stay valid YAML.");
  process.exit(1);
}

const header = [
  "# Selectable UI icons, matching [Heroicons](https://heroicons.com/).",
  "#",
  "# Generated by `npm run icons:sync` from the SVGs in src/icons/ — edit those, not this.",
  "# Reaches the editor as the `icons` dataset; inputs reference it as `values: data.icons`.",
];

const generated = `${[...header, ...ids.flatMap((id) => [`- id: ${id}`, `  name: ${titleize(id)}`])].join("\n")}\n`;
const existing = existsSync(dataPath) ? readFileSync(dataPath, "utf8") : "";

if (mode === "write") {
  if (existing === generated) {
    console.log(`ok     ${dataLabel} (${ids.length} icons)`);
  } else {
    writeFileSync(dataPath, generated);
    console.log(`synced ${dataLabel} (${ids.length} icons)`);
  }
  process.exit(0);
}

if (existing === generated) {
  console.log(`ok     ${dataLabel} (${ids.length} icons)`);
  process.exit(0);
}

const listed = existing
  .split("\n")
  .map((line) => /^- id: (.+)$/.exec(line)?.[1])
  .filter(Boolean);

const onDisk = new Set(ids);
const inData = new Set(listed);
const missing = ids.filter((id) => !inData.has(id));
const orphaned = listed.filter((id) => !onDisk.has(id));

console.error(`DRIFT  ${dataLabel} — the icon dataset is out of sync with src/icons/`);
for (const id of missing) console.error(`   missing:  ${id} (SVG on disk, not in the picker)`);
for (const id of orphaned) console.error(`   orphaned: ${id} (in the picker, no SVG on disk)`);
if (!missing.length && !orphaned.length) {
  console.error("   the ids match but their names or ordering do not");
}

console.error("\nRun: npm run icons:sync");
process.exit(1);
