# Metadata about this component, to be used in the CMS
spec:
  label: Mobile Navigation
  description: A mobile navigation with hamburger menu and slide-out panel.
  icon: device-phone-mobile
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  logo: ""
  navData:
    - name: "Home"
      path: "#"
      children: []
    - name: "Resources"
      path: "#"
      children:
        - name: "Blog"
          path: "#"
          children: []
        - name: "Documentation"
          path: "#"
          children: []
        - name: "Support"
          path: "#"
          children: []
    - name: "Contact"
      path: "#"
      children: []

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  logo: "Logo"
  navData:
    - name: "Home"
      path: "#"
      children: []
    - name: "Resources"
      path: "#"
      children:
        - name: "Blog"
          path: "#"
          children: []
        - name: "Documentation"
          path: "#"
          children: []
        - name: "Support"
          path: "#"
          children: []
    - name: "Contact"
      path: "#"
      children: []

_inputs:
  logo:
    type: text
    label: Logo Text
    comment: Text or HTML for the logo/brand area.
  navData:
    type: text
    label: Navigation Data
    comment: JSON structure defining the navigation items with name, path, and children.
