spec:
  structures:
    - contentBlocks
    - firstContentBlocks
    - secondContentBlocks
  label: Video
  description: "Play a video from YouTube, Vimeo, or your local files."
  icon: data_object
  tags: []

blueprint:
  type: youtube
  id:
  src:
  poster:
  title:

preview:

_inputs:
  type:
    type: select
    options:
      values:
        - youtube
        - vimeo
        - native
    id:
      comment: Enter a video ID from a public video on YouTube or Vimeo
      hidden: 'type == "native"'
    src:
      type: file
      comment: Must be mp4 as this is supported by all modern browsers
      options:
        accepts_mime_types:
          - video/mp4
        paths:
          uploads: /src/assets/videos/
      hidden: 'type != "native"'
    poster:
      comment: The image displayed before the video plays or while it is loading.
      hidden: 'type != "native"'
    autoplay:
      comment: Play the video automatically on load without the user pressing play
